image: Visual Studio 2017

environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
  VSVARSALLPATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
  PYTHON: 'C:\Python37-x64'

cache:
  - r2_dist

install:
  - '%PYTHON%\python.exe -m pip install meson'
  - powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; wget %NINJA_URL% -OutFile ninja.zip" && unzip ninja.zip
  - call "%VSVARSALLPATH%" x64
  - 'git clone https://github.com/radareorg/radare2.git --single-branch --depth 1'
  - 'git clone https://github.com/wargio/r2dec-js --single-branch --depth 1'
  - 'git clone https://github.com/radareorg/r2ghidra-dec.git --single-branch --depth 1 --recurse-submodules'

build_script:
  # Build radare2
  - IF NOT EXIST r2_dist ( %PYTHON%\python.exe radare2\sys\meson.py --release --shared --install=r2_dist )
  - set "PATH=%CD%\r2_dist\bin;%PATH%"
  - ps: $env:R2_LIBDIR = ( 'radare2 -H LIBDIR' )
  - ps: $env:R2_INCDIR = ( 'radare2 -H INCDIR' )
  # Build r2dec
  - '%PYTHON%\Scripts\meson.exe --buildtype=release -Dc_args=-DDUK_USE_DATE_NOW_WINDOWS --prefix=%CD%\dist --libdir=r2dec --datadir=r2dec -Dr2_libdir=%R2_LIBDIR% -Dr2_incdir=%R2_INCDIR% r2dec-js\p build_r2dec'
  - 'ninja -C build_r2dec install'
  # Build r2ghidra
  - 'cmake -G Ninja -DCMAKE_C_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=r2ghidra_dist -DRADARE2_INSTALL_PLUGDIR=dist\r2ghidra-dec -DCMAKE_PREFIX_PATH=%R2_LIBDIR%;%R2_INCDIR% -B build_r2ghidra -S r2ghidra-dec'
  - 'ninja -C build_r2ghidra install'

artifacts:
  - path: dist
