image: Visual Studio 2017

environment:
  NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
  VSVARSALLPATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
  PYTHON: 'C:\Python37-x64'
  
install:
  - %PYTHON%\python.exe -m pip install meson
  - powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; wget %NINJA_URL% -OutFile ninja.zip" && unzip ninja.zip
  - git clone git@github.com:radareorg/radare2.git
  - call "%VSVARSALLPATH%" x64
  - %PYTHON%\python.exe radare2\sys\meson.py --release --shared --install=r2_dist
  
artifacts:
  - path: r2_dist
